'use client'
import { useState, useRef } from 'react'
import { Container, Row, Col, Card, Button, Form, Table, Modal, Badge, InputGroup, Toast, ToastContainer } from 'react-bootstrap'
import { Plus, Search, FileText, DollarSign, Download, Send, Loader } from 'lucide-react'
import { useSupabase } from '../hooks/useSupabase'

// ── PDF export ──────────────────────────────────────────────
async function exportToPDF(invoice) {
  const { default: jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const margin = 48

  // Header gradient bar
  doc.setFillColor(79, 70, 229)
  doc.rect(0, 0, W, 80, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(26)
  doc.setFont('helvetica', 'bold')
  doc.text('ClientPro', margin, 48)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Client Management System', margin, 64)

  // Invoice number top-right
  doc.setFontSize(11)
  doc.text(invoice.invoiceNumber, W - margin, 48, { align: 'right' })
  doc.setFontSize(10)
  doc.text('INVOICE', W - margin, 64, { align: 'right' })

  // Client & dates section
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.text('Bill To', margin, 116)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(71, 85, 105)
  doc.text(invoice.clientName || '—', margin, 134)

  doc.setTextColor(30, 41, 59)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Issue Date:', W - margin - 120, 116)
  doc.text('Due Date:', W - margin - 120, 134)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(71, 85, 105)
  doc.text(invoice.issueDate ? new Date(invoice.issueDate).toLocaleDateString() : '—', W - margin, 116, { align: 'right' })
  doc.text(invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : '—', W - margin, 134, { align: 'right' })

  // Divider
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(1)
  doc.line(margin, 152, W - margin, 152)

  // Table header
  doc.setFillColor(248, 250, 252)
  doc.rect(margin, 160, W - margin * 2, 28, 'F')
  doc.setTextColor(100, 116, 139)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text('DESCRIPTION', margin + 10, 178)
  doc.text('PROJECT', W / 2, 178)
  doc.text('AMOUNT', W - margin - 10, 178, { align: 'right' })

  // Table row
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(30, 41, 59)
  doc.text(invoice.description || 'Services rendered', margin + 10, 208)
  doc.setTextColor(71, 85, 105)
  doc.text(invoice.projectName || '—', W / 2, 208)
  doc.setTextColor(79, 70, 229)
  doc.setFont('helvetica', 'bold')
  doc.text(`$${parseFloat(invoice.amount || 0).toLocaleString()}`, W - margin - 10, 208, { align: 'right' })

  // Total box
  doc.setFillColor(79, 70, 229)
  doc.roundedRect(W - margin - 180, 232, 180, 44, 6, 6, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('TOTAL DUE', W - margin - 90, 250, { align: 'center' })
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(`$${parseFloat(invoice.amount || 0).toLocaleString()}`, W - margin - 90, 268, { align: 'center' })

  // Status badge
  const statusColors = { Paid: [16,185,129], Sent: [79,70,229], Draft: [148,163,184], Overdue: [239,68,68], Cancelled: [51,65,85] }
  const sc = statusColors[invoice.status] || [148,163,184]
  doc.setFillColor(...sc)
  doc.roundedRect(margin, 236, 70, 24, 4, 4, 'F')
  doc.setTextColor(255,255,255)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(invoice.status, margin + 35, 252, { align: 'center' })

  // Notes
  if (invoice.notes) {
    doc.setDrawColor(226, 232, 240)
    doc.line(margin, 296, W - margin, 296)
    doc.setTextColor(100, 116, 139)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text('NOTES', margin, 314)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(71, 85, 105)
    const lines = doc.splitTextToSize(invoice.notes, W - margin * 2)
    doc.text(lines, margin, 330)
  }

  // Footer
  doc.setFillColor(248, 250, 252)
  doc.rect(0, doc.internal.pageSize.getHeight() - 40, W, 40, 'F')
  doc.setTextColor(148, 163, 184)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by ClientPro · clientpro.app', W / 2, doc.internal.pageSize.getHeight() - 16, { align: 'center' })

  doc.save(`${invoice.invoiceNumber}.pdf`)
}

// ── Component ────────────────────────────────────────────────
export default function InvoiceManagement() {
  const [invoices, setInvoices] = useSupabase('invoices', [])
  const [clients] = useSupabase('clients', [])
  const [projects] = useSupabase('projects', [])
  const [showModal, setShowModal] = useState(false)
  const [editingInvoice, setEditingInvoice] = useState(null)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterStatus, setFilterStatus] = useState('All')
  const [sendingId, setSendingId] = useState(null)
  const [downloadingId, setDownloadingId] = useState(null)
  const [toast, setToast] = useState({ show: false, message: '', variant: 'success' })

  const [formData, setFormData] = useState({
    clientId: '', projectId: '', invoiceNumber: '', amount: '',
    description: '', issueDate: new Date().toISOString().split('T')[0],
    dueDate: '', status: 'Draft', notes: ''
  })

  const showToast = (message, variant = 'success') => setToast({ show: true, message, variant })

  const generateInvoiceNumber = () => {
    const now = new Date()
    return `INV-${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}-${String(invoices.length+1).padStart(3,'0')}`
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    const selectedClient = clients.find(c => c.id === parseInt(formData.clientId))
    const selectedProject = projects.find(p => p.id === parseInt(formData.projectId))
    if (editingInvoice) {
      setInvoices(invoices.map(inv => inv.id === editingInvoice.id
        ? { ...formData, id: editingInvoice.id, clientName: selectedClient?.name, projectName: selectedProject?.name, updatedAt: new Date().toISOString() }
        : inv
      ))
    } else {
      setInvoices([...invoices, {
        ...formData,
        invoiceNumber: formData.invoiceNumber || generateInvoiceNumber(),
        clientName: selectedClient?.name || '',
        projectName: selectedProject?.name || '',
        id: Date.now(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      }])
    }
    resetForm()
  }

  const resetForm = () => {
    setFormData({ clientId: '', projectId: '', invoiceNumber: '', amount: '', description: '', issueDate: new Date().toISOString().split('T')[0], dueDate: '', status: 'Draft', notes: '' })
    setEditingInvoice(null)
    setShowModal(false)
  }

  const handleEdit = (invoice) => { setFormData(invoice); setEditingInvoice(invoice); setShowModal(true) }
  const handleDelete = (id) => {
    if (window.confirm('Delete this invoice?')) setInvoices(invoices.filter(inv => inv.id !== id))
  }

  const handleDownload = async (invoice) => {
    setDownloadingId(invoice.id)
    try {
      await exportToPDF(invoice)
      showToast(`${invoice.invoiceNumber} downloaded as PDF`)
    } catch {
      showToast('Failed to generate PDF', 'danger')
    } finally {
      setDownloadingId(null)
    }
  }

  const handleSendEmail = async (invoice) => {
    const client = clients.find(c => c.id === parseInt(invoice.clientId) || c.name === invoice.clientName)
    if (!client?.email) { showToast('Client email not found', 'danger'); return }
    setSendingId(invoice.id)
    try {
      const res = await fetch('/api/invoices/send-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ invoice, clientEmail: client.email })
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      // Mark as Sent
      setInvoices(invoices.map(inv => inv.id === invoice.id ? { ...inv, status: 'Sent', updatedAt: new Date().toISOString() } : inv))
      showToast(`Invoice sent to ${client.email}`)
    } catch (err) {
      showToast(err.message || 'Failed to send email', 'danger')
    } finally {
      setSendingId(null)
    }
  }

  const filteredInvoices = invoices.filter(inv => {
    const matchSearch = inv.invoiceNumber?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        inv.clientName?.toLowerCase().includes(searchTerm.toLowerCase())
    const matchFilter = filterStatus === 'All' || inv.status === filterStatus
    return matchSearch && matchFilter
  })

  const statusVariant = { Draft: 'secondary', Sent: 'primary', Paid: 'success', Overdue: 'danger', Cancelled: 'dark' }
  const totalAmount  = filteredInvoices.reduce((s, i) => s + parseFloat(i.amount || 0), 0)
  const paidAmount   = filteredInvoices.filter(i => i.status === 'Paid').reduce((s, i) => s + parseFloat(i.amount || 0), 0)
  const pendingAmount = totalAmount - paidAmount

  return (
    <Container fluid className="p-4">
      {/* Toast */}
      <ToastContainer position="top-end" className="p-3" style={{ zIndex: 9999 }}>
        <Toast show={toast.show} onClose={() => setToast(t => ({ ...t, show: false }))} delay={3500} autohide bg={toast.variant}>
          <Toast.Body className="text-white fw-600">{toast.message}</Toast.Body>
        </Toast>
      </ToastContainer>

      <div className="page-header d-flex justify-content-between align-items-center">
        <div>
          <h2 className="fw-700 mb-1" style={{ color: '#1e293b' }}>Invoices</h2>
          <p className="text-sm mb-0" style={{ color: '#64748b' }}>{invoices.length} total invoices</p>
        </div>
        <Button variant="primary" onClick={() => setShowModal(true)}>
          <Plus size={16} className="me-2" />New Invoice
        </Button>
      </div>

      {/* Summary Cards */}
      <Row className="mb-4 g-3">
        {[
          { label: 'Total Amount', value: totalAmount, color: '#4f46e5', bg: 'rgba(79,70,229,0.08)' },
          { label: 'Paid',         value: paidAmount,   color: '#10b981', bg: 'rgba(16,185,129,0.08)' },
          { label: 'Pending',      value: pendingAmount, color: '#f59e0b', bg: 'rgba(245,158,11,0.08)' },
        ].map(({ label, value, color, bg }) => (
          <Col md={4} key={label}>
            <Card className="border-0 shadow-sm card-hover rounded-xl">
              <Card.Body className="d-flex align-items-center gap-3 p-4">
                <div className="rounded-xl d-flex align-items-center justify-content-center" style={{ width: 48, height: 48, background: bg }}>
                  <DollarSign size={22} style={{ color }} />
                </div>
                <div>
                  <div className="h4 fw-700 mb-0" style={{ color: '#1e293b' }}>${value.toLocaleString()}</div>
                  <div className="text-sm" style={{ color: '#64748b' }}>{label}</div>
                </div>
              </Card.Body>
            </Card>
          </Col>
        ))}
      </Row>

      {/* Filters */}
      <Card className="shadow-sm border-0 rounded-xl mb-4">
        <Card.Body className="p-3">
          <Row className="align-items-center g-2">
            <Col md={6}>
              <InputGroup>
                <InputGroup.Text className="bg-light border-end-0"><Search size={15} className="text-muted" /></InputGroup.Text>
                <Form.Control className="border-start-0 ps-0" placeholder="Search invoices…" value={searchTerm} onChange={e => setSearchTerm(e.target.value)} />
              </InputGroup>
            </Col>
            <Col md={3}>
              <Form.Select value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
                <option value="All">All Status</option>
                {['Draft','Sent','Paid','Overdue','Cancelled'].map(s => <option key={s}>{s}</option>)}
              </Form.Select>
            </Col>
            <Col md={3} className="text-muted text-sm">
              {filteredInvoices.length} of {invoices.length} invoices
            </Col>
          </Row>
        </Card.Body>
      </Card>

      {/* Table */}
      <Card className="shadow-sm border-0 rounded-xl">
        <Card.Body className="p-0">
          {filteredInvoices.length > 0 ? (
            <div className="table-responsive">
              <Table className="mb-0" hover>
                <thead className="table-light">
                  <tr>
                    <th>Invoice #</th><th>Client</th><th>Project</th>
                    <th>Amount</th><th>Issue Date</th><th>Due Date</th>
                    <th>Status</th><th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredInvoices.map(invoice => (
                    <tr key={invoice.id}>
                      <td className="fw-600">{invoice.invoiceNumber}</td>
                      <td>{invoice.clientName}</td>
                      <td className="text-muted">{invoice.projectName || '—'}</td>
                      <td className="fw-700" style={{ color: '#1e293b' }}>${parseFloat(invoice.amount||0).toLocaleString()}</td>
                      <td className="text-muted text-sm">{new Date(invoice.issueDate).toLocaleDateString()}</td>
                      <td className="text-muted text-sm">{invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString() : '—'}</td>
                      <td><Badge bg={statusVariant[invoice.status] || 'secondary'} className="status-badge">{invoice.status}</Badge></td>
                      <td>
                        <div className="d-flex gap-1">
                          <Button variant="outline-primary" size="sm" onClick={() => handleEdit(invoice)}>Edit</Button>
                          <Button
                            variant="outline-success" size="sm" title="Download PDF"
                            disabled={downloadingId === invoice.id}
                            onClick={() => handleDownload(invoice)}
                          >
                            {downloadingId === invoice.id
                              ? <span className="spinner-border spinner-border-sm" />
                              : <Download size={13} />}
                          </Button>
                          <Button
                            variant="outline-info" size="sm" title="Send via Email"
                            disabled={sendingId === invoice.id}
                            onClick={() => handleSendEmail(invoice)}
                          >
                            {sendingId === invoice.id
                              ? <span className="spinner-border spinner-border-sm" />
                              : <Send size={13} />}
                          </Button>
                          <Button variant="outline-danger" size="sm" onClick={() => handleDelete(invoice.id)}>Delete</Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            </div>
          ) : (
            <div className="text-center py-5">
              <FileText size={48} className="text-muted mb-3" />
              <h5 className="text-muted">No invoices found</h5>
              <p className="text-muted text-sm">Create your first invoice to get started</p>
            </div>
          )}
        </Card.Body>
      </Card>

      {/* Modal */}
      <Modal show={showModal} onHide={resetForm} size="lg">
        <Modal.Header closeButton>
          <Modal.Title className="fw-700">{editingInvoice ? 'Edit Invoice' : 'New Invoice'}</Modal.Title>
        </Modal.Header>
        <Form onSubmit={handleSubmit}>
          <Modal.Body>
            <Row>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label>Client *</Form.Label>
                  <Form.Select required value={formData.clientId} onChange={e => setFormData({...formData, clientId: e.target.value})}>
                    <option value="">Select a client</option>
                    {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                  </Form.Select>
                </Form.Group>
              </Col>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label>Project</Form.Label>
                  <Form.Select value={formData.projectId} onChange={e => setFormData({...formData, projectId: e.target.value})}>
                    <option value="">Select a project (optional)</option>
                    {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                  </Form.Select>
                </Form.Group>
              </Col>
            </Row>
            <Row>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label>Invoice Number</Form.Label>
                  <Form.Control type="text" placeholder="Auto-generated if empty" value={formData.invoiceNumber} onChange={e => setFormData({...formData, invoiceNumber: e.target.value})} />
                </Form.Group>
              </Col>
              <Col md={6}>
                <Form.Group className="mb-3">
                  <Form.Label>Amount *</Form.Label>
                  <Form.Control type="number" step="0.01" required value={formData.amount} onChange={e => setFormData({...formData, amount: e.target.value})} />
                </Form.Group>
              </Col>
            </Row>
            <Form.Group className="mb-3">
              <Form.Label>Description</Form.Label>
              <Form.Control as="textarea" rows={3} placeholder="Services provided…" value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} />
            </Form.Group>
            <Row>
              <Col md={4}>
                <Form.Group className="mb-3">
                  <Form.Label>Issue Date *</Form.Label>
                  <Form.Control type="date" required value={formData.issueDate} onChange={e => setFormData({...formData, issueDate: e.target.value})} />
                </Form.Group>
              </Col>
              <Col md={4}>
                <Form.Group className="mb-3">
                  <Form.Label>Due Date</Form.Label>
                  <Form.Control type="date" value={formData.dueDate} onChange={e => setFormData({...formData, dueDate: e.target.value})} />
                </Form.Group>
              </Col>
              <Col md={4}>
                <Form.Group className="mb-3">
                  <Form.Label>Status</Form.Label>
                  <Form.Select value={formData.status} onChange={e => setFormData({...formData, status: e.target.value})}>
                    {['Draft','Sent','Paid','Overdue','Cancelled'].map(s => <option key={s}>{s}</option>)}
                  </Form.Select>
                </Form.Group>
              </Col>
            </Row>
            <Form.Group className="mb-3">
              <Form.Label>Notes</Form.Label>
              <Form.Control as="textarea" rows={2} placeholder="Additional notes or payment terms…" value={formData.notes} onChange={e => setFormData({...formData, notes: e.target.value})} />
            </Form.Group>
          </Modal.Body>
          <Modal.Footer>
            <Button variant="secondary" onClick={resetForm}>Cancel</Button>
            <Button variant="primary" type="submit">{editingInvoice ? 'Update' : 'Create Invoice'}</Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </Container>
  )
}
